# ========================================
# Application
# ========================================

spring.application.name=${SERVICE_NAME:miniproject}
server.port=${SERVICE_PORT:5555}

# ========================================
# Logging
# ========================================
logging.file.name=logs/history-logging.log
# Default
logging.level.root=INFO
# Application log
logging.level.com.cp.assignment.miniproject=DEBUG

# ========================================
# Batch Input
# ========================================

batch.input.list-a=${BATCH_INPUT_LIST_A:input/listA.csv}
batch.input.list-b=${BATCH_INPUT_LIST_B:input/listB.csv}

# ========================================
# Batch Output
# ========================================

batch.output.matched=${BATCH_OUTPUT_MATCHED:output/matched.csv}
batch.output.missing-in-a=${BATCH_OUTPUT_MISSING_IN_A:output/missing-in-a.csv}
batch.output.missing-in-b=${BATCH_OUTPUT_MISSING_IN_B:output/missing-in-b.csv}
batch.output.error=${BATCH_OUTPUT_ERROR:output/error.csv}

# ========================================
# Spring Batch
# ========================================

# Prevent Spring Batch Job from running automatically on startup
spring.batch.job.enabled=false

# Initialize Spring Batch metadata tables
spring.batch.jdbc.initialize-schema=always

# ========================================
# Batch Scheduler
# ========================================

# false = do not run automatically
# true  = run according to cron
batch.scheduler.enabled=false

# Every 30 seconds
batch.scheduler.cron=*/30 * * * * ?

# Every midnight
#batch.scheduler.cron=0 0 0 * * ?