# ========================================
# Application
# ========================================

spring.application.name=${SERVICE_NAME:miniproject}
server.port=${SERVICE_PORT:5555}

# ========================================
# Logging
# ========================================
logging.file.name=logs/history-logging.log
# Default
logging.level.root=INFO
# Application log
logging.level.com.cp.assignment.miniproject=DEBUG

# ========================================
# Batch Input
# ========================================

batch.input.list-a=${BATCH_INPUT_LIST_A:input/listA.csv}
batch.input.list-b=${BATCH_INPUT_LIST_B:input/listB.csv}

# ========================================
# Batch Output
# ========================================

batch.output.matched=${BATCH_OUTPUT_MATCHED:output/matched.csv}
batch.output.missing-in-a=${BATCH_OUTPUT_MISSING_IN_A:output/missing-in-a.csv}
batch.output.missing-in-b=${BATCH_OUTPUT_MISSING_IN_B:output/missing-in-b.csv}
batch.output.error=${BATCH_OUTPUT_ERROR:output/error.csv}

# ========================================
# Spring Batch
# ========================================

# Prevent Spring Batch Job from running automatically on startup
spring.batch.job.enabled=false


# ========================================
# Batch Scheduler
# ========================================

# false = do not run automatically
# true  = run according to cron
batch.scheduler.enabled=false

# Every 30 seconds
batch.scheduler.cron=*/30 * * * * ?

# Every midnight
#batch.scheduler.cron=0 0 0 * * ?


# ========================================
# H2 Database
# ========================================
#? Database file still exist for  JdbcTemplate ? schema.sql
spring.datasource.url=jdbc:h2:file:./data/reconciliationdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Execute schema-h2.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Initialize Spring Batch metadata tables
spring.batch.jdbc.initialize-schema=always

## ========================================
## Database postgres
## ========================================
#
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/reconciliation}
#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD:postgres}
#spring.datasource.driver-class-name=org.postgresql.Driver

##???????????? initial data ?? database ??????????. ????? ???? schema.sql ??? data.sql ???????????????????? ???????????????????? DB migration
##Spring Boot can automatically create the schema (DDL scripts) of your JDBC DataSource or R2DBC
#spring.batch.jdbc.initialize-schema=always