-- ==========================================
-- SOURCE TABLE: LIST A
-- ==========================================
DROP TABLE IF EXISTS reconciliation_list_a;
DROP TABLE IF EXISTS reconciliation_list_b;
DROP TABLE IF EXISTS reconciliation_matched;
DROP TABLE IF EXISTS reconciliation_missing_in_a;
DROP TABLE IF EXISTS reconciliation_missing_in_b;
DROP TABLE IF EXISTS reconciliation_error;

CREATE TABLE IF NOT EXISTS reconciliation_list_a (
    id BIGSERIAL PRIMARY KEY, --เลขจำนวนเต็มขนาดใหญ่ที่ PostgreSQL จะเพิ่มค่าให้อัตโนมัติ
    row_number VARCHAR(50),
    order_number VARCHAR(100) NOT NULL,
    transaction_date DATE,
    amount NUMERIC(18, 2),
    fees1 NUMERIC(18, 2),
    fees2 NUMERIC(18, 2),
    net_total NUMERIC(18, 2),
    status VARCHAR(50),
    error_message VARCHAR(500),
    reconciled BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_list_a_order_number
ON reconciliation_list_a(order_number);


-- ==========================================
-- SOURCE TABLE: LIST B
-- ==========================================

CREATE TABLE IF NOT EXISTS reconciliation_list_b (
    id BIGSERIAL PRIMARY KEY,--เลขจำนวนเต็มขนาดใหญ่ที่ PostgreSQL จะเพิ่มค่าให้อัตโนมัติ
    row_number VARCHAR(50),
    invoice_number VARCHAR(100) NOT NULL,
    transaction_date DATE,
    amount NUMERIC(18, 2),
    fees1 NUMERIC(18, 2),
    fees2 NUMERIC(18, 2),
    net_total NUMERIC(18, 2),
    card_number VARCHAR(100),
    status VARCHAR(50),
    error_message VARCHAR(500),
    reconciled BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_list_b_invoice_number
ON reconciliation_list_b(invoice_number);


-- ==========================================
-- RESULT TABLE: MATCHED
-- ==========================================

CREATE TABLE IF NOT EXISTS reconciliation_matched (
    id BIGSERIAL PRIMARY KEY,--เลขจำนวนเต็มขนาดใหญ่ที่ PostgreSQL จะเพิ่มค่าให้อัตโนมัติ
    order_number VARCHAR(100),
    invoice_number VARCHAR(100),
    list_a_amount NUMERIC(18, 2),
    list_b_amount NUMERIC(18, 2),
    error_message VARCHAR(500)
);


-- ==========================================
-- RESULT TABLE: MISSING IN A
-- ==========================================

CREATE TABLE IF NOT EXISTS reconciliation_missing_in_a (
    id BIGSERIAL PRIMARY KEY,--เลขจำนวนเต็มขนาดใหญ่ที่ PostgreSQL จะเพิ่มค่าให้อัตโนมัติ
    invoice_number VARCHAR(100),
    transaction_date DATE,
    amount NUMERIC(18, 2),
    error_message VARCHAR(500)
);


-- ==========================================
-- RESULT TABLE: MISSING IN B
-- ==========================================

CREATE TABLE IF NOT EXISTS reconciliation_missing_in_b (
    id BIGSERIAL PRIMARY KEY,--เลขจำนวนเต็มขนาดใหญ่ที่ PostgreSQL จะเพิ่มค่าให้อัตโนมัติ
    order_number VARCHAR(100),
    transaction_date DATE,
    amount NUMERIC(18, 2),
    error_message VARCHAR(500)
);

-- ==========================================
-- RESULT TABLE: ERROR
-- ==========================================
CREATE TABLE reconciliation_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file VARCHAR(255),
    row_number VARCHAR(50),
    reference VARCHAR(255),
    error_message VARCHAR(1000)
);